// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

#![doc = r" This file is automatically generated by `pyo3_opendal::codegen::generate_service_stub`"]
#![allow(clippy::possible_missing_else)]
use opendal_service_s3::{S3_SCHEME, S3Config};
use pyo3::prelude::*;
use pyo3::types::IntoPyDict;
use pyo3::types::PyDict;
use pyo3_opendal::FromConfigurator;
use pyo3_opendal::ToStringMap;
use pyo3_opendal::export::OpendalOperator;
use pyo3_opendal::ocore::Configurator;
use pyo3_opendal::ocore::OperatorUri;
use pyo3_stub_gen::derive::*;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[gen_stub_pyclass]
#[pyclass(get_all, set_all, module = "opendal_service_s3", name = "S3")]
#[derive(Clone, Default, Serialize, Deserialize)]
#[allow(deprecated)]
pub struct PyS3Service {
    #[doc = "access_key_id of this backend."]
    #[doc = ""]
    #[doc = "- If access_key_id is set, we will take user's input first."]
    #[doc = "- If not, we will try to load it from environment."]
    pub access_key_id: Option<String>,
    #[doc = "Allow anonymous will allow opendal to send request without signing"]
    #[doc = "when credential is not loaded."]
    pub allow_anonymous: Option<bool>,
    #[doc = "Set maximum batch operations of this backend."]
    #[doc = ""]
    #[doc = "Some compatible services have a limit on the number of operations in a batch request."]
    #[doc = "For example, R2 could return `Internal Error` while batch delete 1000 files."]
    #[doc = ""]
    #[doc = "Please tune this value based on services' document."]
    #[deprecated(
        since = "0.52.0",
        note = "Please use `delete_max_size` instead of `batch_max_operations`"
    )]
    pub batch_max_operations: Option<usize>,
    #[doc = "bucket name of this backend."]
    #[doc = ""]
    #[doc = "required."]
    pub bucket: String,
    #[doc = "Checksum Algorithm to use when sending checksums in HTTP headers."]
    #[doc = "This is necessary when writing to AWS S3 Buckets with Object Lock enabled for example."]
    #[doc = ""]
    #[doc = "Available options:"]
    #[doc = "- \"crc32c\""]
    #[doc = "- \"md5\""]
    pub checksum_algorithm: Option<String>,
    #[doc = "default storage_class for this backend."]
    #[doc = ""]
    #[doc = "Available values:"]
    #[doc = "- `DEEP_ARCHIVE`"]
    #[doc = "- `GLACIER`"]
    #[doc = "- `GLACIER_IR`"]
    #[doc = "- `INTELLIGENT_TIERING`"]
    #[doc = "- `ONEZONE_IA`"]
    #[doc = "- `EXPRESS_ONEZONE`"]
    #[doc = "- `OUTPOSTS`"]
    #[doc = "- `REDUCED_REDUNDANCY`"]
    #[doc = "- `STANDARD`"]
    #[doc = "- `STANDARD_IA`"]
    #[doc = ""]
    #[doc = "S3 compatible services don't support all of them"]
    pub default_storage_class: Option<String>,
    #[doc = "Set the maximum delete size of this backend."]
    #[doc = ""]
    #[doc = "Some compatible services have a limit on the number of operations in a batch request."]
    #[doc = "For example, R2 could return `Internal Error` while batch delete 1000 files."]
    #[doc = ""]
    #[doc = "Please tune this value based on services' document."]
    pub delete_max_size: Option<usize>,
    #[doc = "Disable config load so that opendal will not load config from"]
    #[doc = "environment."]
    #[doc = ""]
    #[doc = "For examples:"]
    #[doc = ""]
    #[doc = "- envs like `AWS_ACCESS_KEY_ID`"]
    #[doc = "- files like `~/.aws/config`"]
    pub disable_config_load: Option<bool>,
    #[doc = "Disable load credential from ec2 metadata."]
    #[doc = ""]
    #[doc = "This option is used to disable the default behavior of opendal"]
    #[doc = "to load credential from ec2 metadata, a.k.a., IMDSv2"]
    pub disable_ec2_metadata: Option<bool>,
    #[doc = "OpenDAL uses List Objects V2 by default to list objects."]
    #[doc = "However, some legacy services do not yet support V2."]
    #[doc = "This option allows users to switch back to the older List Objects V1."]
    pub disable_list_objects_v2: Option<bool>,
    #[doc = "Disable stat with override so that opendal will not send stat request with override queries."]
    #[doc = ""]
    #[doc = "For example, R2 doesn't support stat with `response_content_type` query."]
    pub disable_stat_with_override: Option<bool>,
    #[doc = "Disable write with if match so that opendal will not send write request with if match headers."]
    #[doc = ""]
    #[doc = "For example, Ceph RADOS S3 doesn't support write with if matched."]
    pub disable_write_with_if_match: Option<bool>,
    #[doc = "Indicates whether the client agrees to pay for the requests made to the S3 bucket."]
    pub enable_request_payer: Option<bool>,
    #[doc = "is bucket versioning enabled for this bucket"]
    pub enable_versioning: Option<bool>,
    #[doc = "Enable virtual host style so that opendal will send API requests"]
    #[doc = "in virtual host style instead of path style."]
    #[doc = ""]
    #[doc = "- By default, opendal will send API to `https://s3.us-east-1.amazonaws.com/bucket_name`"]
    #[doc = "- Enabled, opendal will send API to `https://bucket_name.s3.us-east-1.amazonaws.com`"]
    pub enable_virtual_host_style: Option<bool>,
    #[doc = "Enable write with append so that opendal will send write request with append headers."]
    pub enable_write_with_append: Option<bool>,
    #[doc = "endpoint of this backend."]
    #[doc = ""]
    #[doc = "Endpoint must be full uri, e.g."]
    #[doc = ""]
    #[doc = "- AWS S3: `https://s3.amazonaws.com` or `https://s3.{region}.amazonaws.com`"]
    #[doc = "- Cloudflare R2: `https://<ACCOUNT_ID>.r2.cloudflarestorage.com`"]
    #[doc = "- Aliyun OSS: `https://{region}.aliyuncs.com`"]
    #[doc = "- Tencent COS: `https://cos.{region}.myqcloud.com`"]
    #[doc = "- Minio: `http://127.0.0.1:9000`"]
    #[doc = ""]
    #[doc = "If user inputs endpoint without scheme like \"s3.amazonaws.com\", we"]
    #[doc = "will prepend \"https://\" before it."]
    #[doc = ""]
    #[doc = "- If endpoint is set, we will take user's input first."]
    #[doc = "- If not, we will try to load it from environment."]
    #[doc = "- If still not set, default to `https://s3.amazonaws.com`."]
    pub endpoint: Option<String>,
    #[doc = "external_id for this backend."]
    pub external_id: Option<String>,
    #[doc = "Region represent the signing region of this endpoint. This is required"]
    #[doc = "if you are using the default AWS S3 endpoint."]
    #[doc = ""]
    #[doc = "If using a custom endpoint,"]
    #[doc = "- If region is set, we will take user's input first."]
    #[doc = "- If not, we will try to load it from environment."]
    pub region: Option<String>,
    #[doc = "role_arn for this backend."]
    #[doc = ""]
    #[doc = "If `role_arn` is set, we will use already known config as source"]
    #[doc = "credential to assume role with `role_arn`."]
    pub role_arn: Option<String>,
    #[doc = "role_session_name for this backend."]
    pub role_session_name: Option<String>,
    #[doc = "root of this backend."]
    #[doc = ""]
    #[doc = "All operations will happen under this root."]
    #[doc = ""]
    #[doc = "default to `/` if not set."]
    pub root: Option<String>,
    #[doc = "secret_access_key of this backend."]
    #[doc = ""]
    #[doc = "- If secret_access_key is set, we will take user's input first."]
    #[doc = "- If not, we will try to load it from environment."]
    pub secret_access_key: Option<String>,
    #[doc = "server_side_encryption for this backend."]
    #[doc = ""]
    #[doc = "Available values: `AES256`, `aws:kms`."]
    pub server_side_encryption: Option<String>,
    #[doc = "server_side_encryption_aws_kms_key_id for this backend"]
    #[doc = ""]
    #[doc = "- If `server_side_encryption` set to `aws:kms`, and `server_side_encryption_aws_kms_key_id`"]
    #[doc = "is not set, S3 will use aws managed kms key to encrypt data."]
    #[doc = "- If `server_side_encryption` set to `aws:kms`, and `server_side_encryption_aws_kms_key_id`"]
    #[doc = "is a valid kms key id, S3 will use the provided kms key to encrypt data."]
    #[doc = "- If the `server_side_encryption_aws_kms_key_id` is invalid or not found, an error will be"]
    #[doc = "returned."]
    #[doc = "- If `server_side_encryption` is not `aws:kms`, setting `server_side_encryption_aws_kms_key_id`"]
    #[doc = "is a noop."]
    pub server_side_encryption_aws_kms_key_id: Option<String>,
    #[doc = "server_side_encryption_customer_algorithm for this backend."]
    #[doc = ""]
    #[doc = "Available values: `AES256`."]
    pub server_side_encryption_customer_algorithm: Option<String>,
    #[doc = "server_side_encryption_customer_key for this backend."]
    #[doc = ""]
    #[doc = "Value: BASE64-encoded key that matches algorithm specified in"]
    #[doc = "`server_side_encryption_customer_algorithm`."]
    pub server_side_encryption_customer_key: Option<String>,
    #[doc = "Set server_side_encryption_customer_key_md5 for this backend."]
    #[doc = ""]
    #[doc = "Value: MD5 digest of key specified in `server_side_encryption_customer_key`."]
    pub server_side_encryption_customer_key_md5: Option<String>,
    #[doc = "session_token (aka, security token) of this backend."]
    #[doc = ""]
    #[doc = "This token will expire after sometime, it's recommended to set session_token"]
    #[doc = "by hand."]
    pub session_token: Option<String>,
}
impl From<PyS3Service> for S3Config {
    #[allow(deprecated)]
    fn from(opts: PyS3Service) -> Self {
        let mut cfg = S3Config::default();
        cfg.access_key_id = opts.access_key_id;
        if let Some(v) = opts.allow_anonymous {
            cfg.allow_anonymous = v;
        }
        cfg.batch_max_operations = opts.batch_max_operations;
        cfg.bucket = opts.bucket;
        cfg.checksum_algorithm = opts.checksum_algorithm;
        cfg.default_storage_class = opts.default_storage_class;
        cfg.delete_max_size = opts.delete_max_size;
        if let Some(v) = opts.disable_config_load {
            cfg.disable_config_load = v;
        }
        if let Some(v) = opts.disable_ec2_metadata {
            cfg.disable_ec2_metadata = v;
        }
        if let Some(v) = opts.disable_list_objects_v2 {
            cfg.disable_list_objects_v2 = v;
        }
        if let Some(v) = opts.disable_stat_with_override {
            cfg.disable_stat_with_override = v;
        }
        if let Some(v) = opts.disable_write_with_if_match {
            cfg.disable_write_with_if_match = v;
        }
        if let Some(v) = opts.enable_request_payer {
            cfg.enable_request_payer = v;
        }
        if let Some(v) = opts.enable_versioning {
            cfg.enable_versioning = v;
        }
        if let Some(v) = opts.enable_virtual_host_style {
            cfg.enable_virtual_host_style = v;
        }
        if let Some(v) = opts.enable_write_with_append {
            cfg.enable_write_with_append = v;
        }
        cfg.endpoint = opts.endpoint;
        cfg.external_id = opts.external_id;
        cfg.region = opts.region;
        cfg.role_arn = opts.role_arn;
        cfg.role_session_name = opts.role_session_name;
        cfg.root = opts.root;
        cfg.secret_access_key = opts.secret_access_key;
        cfg.server_side_encryption = opts.server_side_encryption;
        cfg.server_side_encryption_aws_kms_key_id = opts.server_side_encryption_aws_kms_key_id;
        cfg.server_side_encryption_customer_algorithm =
            opts.server_side_encryption_customer_algorithm;
        cfg.server_side_encryption_customer_key = opts.server_side_encryption_customer_key;
        cfg.server_side_encryption_customer_key_md5 = opts.server_side_encryption_customer_key_md5;
        cfg.session_token = opts.session_token;
        cfg
    }
}
#[gen_stub_pymethods]
#[pymethods]
impl PyS3Service {
    #[new]
    # [pyo3 (signature = (* , * * kwargs))]
    fn new(kwargs: Option<&Bound<PyDict>>) -> PyResult<Self> {
        Self::from_config(kwargs)
    }
    #[staticmethod]
    # [pyo3 (signature = (* * kwargs))]
    pub fn from_config(kwargs: Option<&Bound<PyDict>>) -> PyResult<Self> {
        let map: HashMap<String, String> =
            kwargs.map(|d| d.extract()).transpose()?.unwrap_or_default();
        let cfg = S3Config::from_iter(map).map_err(pyo3_opendal::format_pyerr)?;
        Self::from_configurator(&cfg)
    }
    #[staticmethod]
    # [pyo3 (signature = (uri , * * kwargs))]
    pub fn from_uri(uri: &str, kwargs: Option<&Bound<PyDict>>) -> PyResult<Self> {
        let map: HashMap<String, String> =
            kwargs.map(|d| d.extract()).transpose()?.unwrap_or_default();
        let cfg = OperatorUri::new(uri, map)
            .and_then(|u| S3Config::from_uri(&u))
            .map_err(pyo3_opendal::format_pyerr)?;
        Self::from_configurator(&cfg)
    }
    # [gen_stub (override_return_type (type_repr = "opendal.AsyncOperator" , imports = ("opendal")))]
    pub fn to_async_operator(&self, py: Python) -> PyResult<OpendalOperator> {
        let cfg: S3Config = self.clone().into();
        let map = cfg.to_string_map()?;
        crate::__build_operator__(S3_SCHEME.into(), true, Some(&map.into_py_dict(py)?))
    }
    # [gen_stub (override_return_type (type_repr = "opendal.Operator" , imports = ("opendal")))]
    pub fn to_operator(&self, py: Python) -> PyResult<OpendalOperator> {
        let cfg: S3Config = self.clone().into();
        let map = cfg.to_string_map()?;
        crate::__build_operator__(S3_SCHEME.into(), false, Some(&map.into_py_dict(py)?))
    }
}
