// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

#![doc = r" This file is automatically generated by `pyo3_opendal::codegen::generate_layer_stub`"]
use crate::opyo3;
use opendal_layer_mime_guess::MimeGuessLayer;
use pyo3::prelude::*;
use pyo3_stub_gen::derive::*;
#[gen_stub_pyclass]
# [pyclass (name = "MimeGuessLayer" , extends = opyo3 :: PyLayer)]
#[derive(Clone)]
pub struct PyMimeGuessLayer(MimeGuessLayer);
impl opyo3::PythonLayer for PyMimeGuessLayer {
    fn layer(&self, op: opyo3::ocore::Operator) -> opyo3::ocore::Operator {
        op.layer(self.0.clone())
    }
}
#[gen_stub_pymethods]
#[pymethods]
impl PyMimeGuessLayer {
    #[doc = "Create a new MimeGuessLayer."]
    #[doc = ""]
    #[doc = "Returns"]
    #[doc = "-------"]
    #[doc = "MimeGuessLayer"]
    # [gen_stub (override_return_type (type_repr = "opendal.layers.Layer" , imports = ("opendal")))]
    #[new]
    # [pyo3 (signature = ())]
    fn new() -> PyResult<PyClassInitializer<Self>> {
        let mut layer = MimeGuessLayer::default();
        let class = PyClassInitializer::from(opyo3::PyLayer::new()?).add_subclass(Self(layer));
        Ok(class)
    }
}
