// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

#![doc = r" This file is automatically generated by `pyo3_opendal::codegen::generate_layer_stub`"]
#![allow(clippy::possible_missing_else)]
use crate::opyo3;
use opendal_layer_retry::RetryLayer;
use pyo3::prelude::*;
use pyo3_stub_gen::derive::*;
#[gen_stub_pyclass]
# [pyclass (name = "RetryLayer" , extends = opyo3 :: PyLayer)]
#[derive(Clone)]
pub struct PyRetryLayer(RetryLayer);
impl opyo3::PythonLayer for PyRetryLayer {
    fn layer(&self, op: opyo3::ocore::Operator) -> opyo3::ocore::Operator {
        op.layer(self.0.clone())
    }
}
#[gen_stub_pymethods]
#[pymethods]
impl PyRetryLayer {
    #[doc = "Create a new RetryLayer."]
    #[doc = ""]
    #[doc = "Parameters"]
    #[doc = "----------"]
    #[doc = "factor : Optional[float]"]
    #[doc = "    Set factor of current backoff."]
    #[doc = "    # Panics"]
    #[doc = "    This function will panic if input factor smaller than `1.0`."]
    #[doc = "jitter : Optional[bool]"]
    #[doc = "    Set jitter of current backoff."]
    #[doc = "    If jitter is enabled, ExponentialBackoff will add a random jitter in `[0, min_delay)"]
    #[doc = "    to current delay."]
    #[doc = "max_delay : Optional[float]"]
    #[doc = "    Set max_delay of current backoff."]
    #[doc = "    Delay will not increase if current delay is larger than max_delay."]
    #[doc = "max_times : Optional[int]"]
    #[doc = "    Set max_times of current backoff."]
    #[doc = "    Backoff will return `None` if max times is reaching."]
    #[doc = "min_delay : Optional[float]"]
    #[doc = "    Set min_delay of current backoff."]
    #[doc = ""]
    #[doc = "Returns"]
    #[doc = "-------"]
    #[doc = "RetryLayer"]
    # [gen_stub (override_return_type (type_repr = "opendal.layers.Layer" , imports = ("opendal")))]
    #[new]
    # [pyo3 (signature = (factor = None , jitter = false , max_delay = None , max_times = None , min_delay = None))]
    #[allow(unused)]
    fn new(
        factor: Option<f32>,
        jitter: bool,
        max_delay: Option<std::time::Duration>,
        max_times: Option<usize>,
        min_delay: Option<std::time::Duration>,
    ) -> PyResult<PyClassInitializer<Self>> {
        let mut layer = RetryLayer::default();
        if let Some(v) = factor {
            layer = layer.with_factor(v);
        }
        if jitter {
            layer = layer.with_jitter();
        }
        if let Some(v) = max_delay {
            layer = layer.with_max_delay(v);
        }
        if let Some(v) = max_times {
            layer = layer.with_max_times(v);
        }
        if let Some(v) = min_delay {
            layer = layer.with_min_delay(v);
        }
        let class = PyClassInitializer::from(opyo3::PyLayer::new()?).add_subclass(Self(layer));
        Ok(class)
    }
}
