# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import datetime
import typing

import opendal

__all__ = [
    "RetryLayer",
]

@typing.final
class RetryLayer:
    def __new__(
        cls,
        factor: builtins.float | None = None,
        jitter: builtins.bool = False,
        max_delay: datetime.timedelta | None = None,
        max_times: builtins.int | None = None,
        min_delay: datetime.timedelta | None = None,
    ) -> opendal.layers.Layer:
        r"""
        Create a new RetryLayer.

        Parameters
        ----------
        factor : float, optional
           Set factor of current backoff.
           # Panics
           This function will panic if input factor smaller than `1.0`.
        jitter : bool, optional
           Set jitter of current backoff.
           If jitter is enabled, ExponentialBackoff will add a random jitter in `[0, min_delay)
           to current delay.
        max_delay : datetime.timedelta, optional
           Set max_delay of current backoff.
           Delay will not increase if current delay is larger than max_delay.
        max_times : int, optional
           Set max_times of current backoff.
           Backoff will return `None` if max times is reaching.
        min_delay : datetime.timedelta, optional
           Set min_delay of current backoff.

        Returns
        -------
        RetryLayer
        """
