# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing

@typing.final
class S3PyOperator:
    r"""
    The blocking equivalent of `S3PyAsyncOperator` for s3 service.

    `S3PyOperator` is the entry point for all blocking APIs for s3 service.

    See Also
    --------
    S3PyAsyncOperator
    """

    def __new__(cls, **kwargs: typing.Any) -> S3PyOperator:
        r"""
        Create a new blocking `Operator` for s3 service.

        Parameters
        ----------
        **kwargs : dict
            The options for the service.

        Returns
        -------
        Operator
            The new operator.
        """
