# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing

import opendal

__all__ = [
    "Fs",
]

@typing.final
class Fs:
    @property
    def root(self) -> builtins.str | None:
        r"""Root dir for backend."""
    @root.setter
    def root(self, value: builtins.str | None) -> None:
        r"""Root dir for backend."""
    @property
    def atomic_write_dir(self) -> builtins.str | None:
        r"""Tmp dir for atomic write."""
    @atomic_write_dir.setter
    def atomic_write_dir(self, value: builtins.str | None) -> None:
        r"""Tmp dir for atomic write."""
    @staticmethod
    def from_config(**kwargs: typing.Any) -> Fs: ...
    @staticmethod
    def from_uri(uri: builtins.str, **kwargs: typing.Any) -> Fs: ...
    def to_async_operator(self) -> opendal.AsyncOperator: ...
    def to_operator(self) -> opendal.Operator: ...
